### ISSUE TITLE
Hotkey does not work on Windows

### ISSUE THREAD

**Issue by sotakal** [marconi/switch-notebook#2]
The switch-notebook hotkey is set up as Win+P on Windows, which is a system-wide hotkey reserved for switching display output:
![image](https://user-images.githubusercontent.com/64089225/80945912-2a05a500-8ded-11ea-886b-78675726c6a2.png)

A more suitable hotkey would be preferable, e.g. Ctrl+P or Ctrl+Space (personally I'd prefer the latter)

**Comment by marconi** [comment]
~~Cool, so looks like we finally have windows users. There might be a way to do specific hot-keys for windows, we'll see.~~

You can create a custom key mapping instead like: ` 'ctrl-p': 'switch-notebook:toggle'`. You need to add that on your `keymap.cson` file.

**Comment by marconi** [comment]
I presume this is solved now, closing. 😜
