### ISSUE TITLE
Screenshot broken

### ISSUE THREAD

**Issue by craftzdog** [marconi/switch-notebook#4]
Hello, the Inkdrop author here,

Thank you for creating the great plugin!
BTW, I found that the screenshot is not showing on the plugin page:

<img width="408" alt="Screen Shot 2020-09-07 at 13 53 31" src="https://user-images.githubusercontent.com/1332805/92349575-85380300-f111-11ea-887e-0378ca5d7345.png">

Could you fix it?
Best regards

**Comment by marconi** [comment]
@craftzdog Fixed! Thanks for letting me know, apparently my server was down. 😅
