### ISSUE TITLE
The plugin doesn't work on Inkdrop 5.3.1

### ISSUE THREAD

**Issue by ryukiyokoo1164** [marconi/switch-notebook#6]
Hello. I installed the plugin on Inkdrop 5.3.1 but it doesn't work.
I encountered an error.
Please check the attached image.
![image](https://user-images.githubusercontent.com/53246723/126416477-21eedda3-d727-430a-9b12-bb4771ba2daa.png)

**Comment by marconi** [comment]
@ryukiyokoo1164 Thanks for reporting, I've already pushed new changes to upgrade the package but I'm having issues publishing it. I'll take a look at it again tonight, but for now you can clone the repo and link it locally. Not ideal I know but at least you only have to do it once. 😉

**Comment by marconi** [comment]
@ryukiyokoo1164 Alright `0.2.0` has been released, you should be able to install it. Don't forget to restart Inkdrop after installation. 🙌

**Comment by ryukiyokoo1164** [comment]
@marconi Hi, thank you for the reply! I'm going to try the new version! 😄

**Comment by ryukiyokoo1164** [comment]
Hi,
The new version works! Thank you so much! It is really helpful. 😊

**Comment by marconi** [comment]
@ryukiyokoo1164 Glad it helps, I use it everyday as well. 🙌
