### ISSUE TITLE
Adding "All Notes" in the module

### ISSUE THREAD

**Issue by ryukiyokoo1164** [marconi/switch-notebook#7]
Hello.
Thank you for developing a wonderful plugin.
It is really helpful for me.
Could you please consider adding "All Notes" in the module?

Best regards,
Ryuki

![image](https://user-images.githubusercontent.com/53246723/127593732-e1af705e-a46d-4d4b-ada8-ab1c540787bf.png)

**Comment by marconi** [comment]
@ryukiyokoo1164 Cool, that's something I can consider but not something I'd use all the time. In the meantime, you're welcome to open a PR if you're up for the challenge. 😉 Should be straight-forward to implement.

**Comment by ryukiyokoo1164** [comment]
@marconi Thank you for the reply! OK, I'm going to challenge PullRequest!
