### ISSUE TITLE
Use `React.createRef` instead of a string ref

### ISSUE THREAD

**Issue by craftzdog** [marconi/switch-notebook#8]
Hi,

Thanks for creating a plugin!
I got a crash report from a user on the user forum here: https://forum.inkdrop.app/t/app-keeps-crashing/2657/6

He gets the following React error on the app launch: https://reactjs.org/docs/error-decoder.html/?invariant=290&args%5B%5D=dialog

And he reported that it's resolved once he disabled this plugin.
I guess that's because this plugin uses a string Ref here: https://github.com/marconi/switch-notebook/blob/master/lib/switch-notebook-message-dialog.js#L85
I don't know why it causes the app crash but it'd be nice to replace it with `React.createRef`.

**Comment by marconi** [comment]
Thanks @craftzdog, I'll look into it. 👍🏼

**Comment by marconi** [comment]
@craftzdog Just published `0.2.1`, let me also reply on the thread.
