### ISSUE TITLE
Screenshot not showing on plugin page

### ISSUE THREAD

**Issue by craftzdog** [marconi/switch-notebook#9]
Hi! Thanks for making the great plugin.
I found a small issue on the plugin page:

https://my.inkdrop.app/plugins/switch-notebook

The screenshot is not showing due to the CORS restriction as it's on `github.marconijr.com`.
Could you please update it?

**Comment by marconi** [comment]
@craftzdog Updated it, but the plugin page (https://my.inkdrop.app/plugins/switch-notebook) still seems to be cached. How do I invalidate it?

**Comment by craftzdog** [comment]
You have to republish the plugin to update the README. Here are the steps to do that:

https://forum.inkdrop.app/t/how-to-re-publish-a-plugin-with-the-same-version/2256/4?u=craftzdog

**Comment by marconi** [comment]
@craftzdog Just did and still showing the old page:

```
➜ ipm publish -t v0.2.2 --allow-same-version
Publishing switch-notebook@v0.2.2 ✓
```

<img width="898" alt="CleanShot 2023-10-23 at 10 00 41@2x" src="https://github.com/marconi/switch-notebook/assets/49830/c4544230-5063-448c-8820-e1539fb26250">

**Comment by craftzdog** [comment]
The readme was correctly updated but the browser still blocks the image because it redirects to `github-production-user-asset-6210df.s3.amazonaws.com` 🤔

**Comment by craftzdog** [comment]
Could you replace it with `https://user-images.githubusercontent.com/49830/277161558-4c504f32-95ea-450e-8ca4-225686c7bd51.png`?
It looks like allowing `github-production-user-asset-*.s3.amazonaws.com` is not possible in CORS.

**Comment by marconi** [comment]
@craftzdog Updated 🎉 
 
 
<img width="832" alt="CleanShot 2023-11-02 at 22 31 48@2x" src="https://github.com/marconi/switch-notebook/assets/49830/ae705089-342a-4288-8f01-d9487c492a9a">

we should probably add this as a note on forum for when people encounter the same thing.
